"""empty message

Revision ID: 998223d7cdc4
Revises: d6512e1fdebd
Create Date: 2023-11-09 08:18:22.047554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998223d7cdc4'
down_revision = 'd6512e1fdebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
