"""Added Location and Date of birth

Revision ID: a70fb088ca12
Revises: 50e09bdeda13
Create Date: 2023-11-22 14:48:03.993685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a70fb088ca12'
down_revision = '50e09bdeda13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dof', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('about_author')
        batch_op.drop_column('favourite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_color', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('about_author', mysql.TEXT(), nullable=True))
        batch_op.drop_column('bio')
        batch_op.drop_column('location')
        batch_op.drop_column('dof')

    # ### end Alembic commands ###
